name: CI/CD Digital Ocean

on:
  push:
    branches: [main]
env:
  REACT_APP_PROD: ${{secrets.REACT_APP_PROD}}
  REACT_APP_SERVER_URL: ${{secrets.REACT_APP_SERVER_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and Build
        run: npm install && npm run build

      - name: Upload to Client Digital Ocean
        uses: appleboy/scp-action@master # This is the action
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dist" # Path to the directory you want to copy
          target: "/var/www/html/admin" # Path to the directory you want to copy to

