name: CI/CD Digital Ocean PROD

on:
  push:
    branches: [main]
env:
  VITE_PRODUCTION: ${{secrets.VITE_PRODUCTION_PROD}}
  VITE_SERVER_URL: ${{secrets.VITE_SERVER_URL_PROD}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and Build
        run: npm install && npm run build

      - name: Upload to Client Digital Ocean
        uses: appleboy/scp-action@master # This is the action
        with:
          host: ${{secrets.SSH_HOST_PROD}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'dist' # Path to the directory you want to copy
          target: '/var/www/html/admin' # Path to the directory you want to copy to
